//
// Created by glebo on 20.04.2026.
//

#ifndef SECURE_TOURISM_DB_SYSTEM_ENCRYPTIONMANAGER_H
#define SECURE_TOURISM_DB_SYSTEM_ENCRYPTIONMANAGER_H



class EncryptionManager {

};



#endif //SECURE_TOURISM_DB_SYSTEM_ENCRYPTIONMANAGER_H
